//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureSoftWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbFutureSoftEntities : DbContext
    {
        public dbFutureSoftEntities()
            : base("name=dbFutureSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_Urun> tbl_Urun { get; set; }
    
        public virtual int spINSERT_tbl_Kullanici(string kAdi, string kSifre, string isim, string soyisim, string tel, string adres)
        {
            var kAdiParameter = kAdi != null ?
                new ObjectParameter("kAdi", kAdi) :
                new ObjectParameter("kAdi", typeof(string));
    
            var kSifreParameter = kSifre != null ?
                new ObjectParameter("kSifre", kSifre) :
                new ObjectParameter("kSifre", typeof(string));
    
            var isimParameter = isim != null ?
                new ObjectParameter("isim", isim) :
                new ObjectParameter("isim", typeof(string));
    
            var soyisimParameter = soyisim != null ?
                new ObjectParameter("soyisim", soyisim) :
                new ObjectParameter("soyisim", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spINSERT_tbl_Kullanici", kAdiParameter, kSifreParameter, isimParameter, soyisimParameter, telParameter, adresParameter);
        }
    }
}
