//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Urun
    {
        public int urunID { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public string urunAdi { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public string koordinatX { get; set; }
        public string koordinatY { get; set; }
        public string imagePathUrl { get; set; }
    
        public virtual tbl_Kategori tbl_Kategori { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
